Eyevinn/orchestration-gui

.github/workflows/dispatch.yml
Dockerfile

This will enable to manually trigger a GItHub action that builds a Docker image and push to GitHub container registry in this repo. The GUI_VERSION is set on build time and generated from the short `sha` of the latest commit. This is also the tag for the Docker image.

chore: trigger build of Docker image

---

src/api/manager/job/syncInventory.ts
src/components/filter/FilterDropdown.tsx
src/components/filter/FilterOptions.tsx
src/components/filter/SortSelect.tsx
src/components/inventory/EditViewContext.tsx
src/components/inventory/editView/GeneralSettings.tsx
src/components/sourceListItem/SourceListItem.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/Source.ts

This PR:
- Adds a lastConnected to the Source dB schema, which updates on inventory syncing if the source is found in the api
- Adds functionality to the FilterDropdown to sort sources based on their lastConnected date, with a button to reverse the order of the sorting
**No sorting selected (in this case, the 'reverse sort order' button is disabled):**
**Sort on most recent is selected, reverse button NOT pressed:**
**Sort on most recent is selected, with the reverse button pressed:**

Source management sorting

---

src/api/manager/job/syncInventory.ts

The problem was that we were comparing inventorySource.type with apiSource.type but they are not the same type and are incomparable

fix: bug solve for incorrect gone assignment

---

src/api/agileLive/pipelines/multiviews/multiviews.ts
src/api/agileLive/pipelines/streams/streams.ts
src/api/manager/workflow.ts
src/app/api/manager/streams/[id]/route.ts
src/app/production/[id]/page.tsx
src/components/modal/configureOutputModal/ConfigureOutputModal.tsx
src/components/modal/configureOutputModal/Input.tsx
src/components/modal/configureOutputModal/MultiviewSettings.tsx
src/components/startProduction/StartProductionButton.tsx
src/hooks/items/addSetupItem.ts
src/hooks/multiviews.ts
src/hooks/streams.ts
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/pipeline.ts

When setting up a production this allows for adding multiple multiviews to each production, for the possibility of having multiviews with different setups.
Added buttons to add and remove additional multiviewers, when only one multiview remains the button is removed.
When production is running, all multiviewers can be located in the control window to the right.
An easier way to start all multiviewers at once is to install mpv-player ("brew install mpv" on mac) and then run all srt-links in the command-line "mpv srt://0.0.0.0:1234 & mpv srt://0.0.0.0:2345 & mpv srt://0.0.0.0:3456"

Create multiple multiview outputs per production

---

src/components/filter/FilterDropdown.tsx
src/components/filter/FilterOptions.tsx
src/components/inventory/Inventory.tsx

Solves filter errors:
1. The previous logic did not handle the case where there were no items matching the filter criteria. Which was the case for SRT sources.
2. Adds new type of ingest_type to filter on: Test pattern (where ingest source.type === MediaSourceGenerator).
2. Now, if no filters are on, no sources are shown. By default NDI, SDI, and SRT filters are on and the Test Pattern filter is off.

fix: bug fixes on filter

---

src/app/production/[id]/page.tsx
src/components/sourceCards/SourceCards.tsx

There was a bug that a user in locked mode could still move around sources in a production, this disabled that possibility.

fix: solve lock bug

---

src/components/sourceCard/SourceCard.tsx

Solves the issue with a locked user still being able to remove sources from a production, probably a result from merge conflicts

fix: could remove sources from prod when locked

---

src/components/filter/FilterOptions.tsx
src/components/sourceList/SourceList.tsx

There was a problem with the filter that if no sources matches the filter, all sources were shown.

fix: filter bug, showing all instead of none

---

.env.sample
src/api/manager/workflow.ts
src/components/startProduction/StartProductionFeed.tsx
src/components/startProduction/StopProductionFeed.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/production.ts

Solves the bug that you could not start a production without having a working websocket URL, even if your production didn't contain media player/html sources. Improved error messages for websocket errors as well.
I also updated the WS variable in env.sample to provide information about what the variable should include

fix: bug ws url needed

---

src/components/sourceCard/SourceCard.tsx

Solves the problem with the input and server information not showing on ingest sources. The problem was simply that they were underneath the thumbnail, so the only code added is z-10 to both text-classNames.

fix: bug with input slot not showing

---

src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts

Solves the bug with identical hover-messages on remove and add multiview. It was not part of i18n, so added both of them to the lists and updated the component.

fix: updated title on remove and add multiview in multiview config

---

src/api/ateliereLive/ingest.ts
src/api/ateliereLive/pipelines/streams/streams.ts
src/api/manager/productions.ts
src/api/manager/workflow.ts
src/app/api/manager/ingests/source_id/[ingest_name]/[ingest_source_name]/route.ts
src/app/api/manager/ingests/streams/[ingest_name]/[ingest_source_name]/route.ts
src/app/api/manager/productions/[id]/[pipeline_id]/[ingest_name]/[ingest_source_name]/route.ts
src/app/api/manager/sources/[ingest_name]/[source_name]/thumbnail/route.ts
src/app/api/manager/srt/[ingest_name]/[ingest_source_name]/route.ts
src/app/api/manager/streams/[id]/route.ts
src/app/production/[id]/page.tsx
src/components/modal/ConfigureAlignmentLatencyModal.tsx
src/components/sourceCard/SourceCard.tsx
src/components/sourceCards/SourceCards.tsx
src/hooks/ingests.ts
src/hooks/productions.ts
src/hooks/streams.ts
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/pipeline.ts

- Adds the possibility to configure alignment and latency for a pipeline stream during a running production.
Steps to do so:
1. Start a production, and click the settings button on the source card.
2. Set new values
3. On save: alignment_ms and latency is saved on the pipeline with the source's sourceId as a key. A PATCH request to update the stream's alignment with the new value is also done.
I also added error handeling in case the latency value is set to higher value than the alignment, since if that's the case it will not be possibly to start a production.
4. On stop and start, there are checks when each stream is created to see if the alignment/latency for that source on each respective pipeline and in that case that value is used, otherwise the pipeline's 'global' value is used.
- I …

feat: add modal for alignment and latency config

---

src/api/ateliereLive/pipelines/multiviews/multiviews.ts
src/api/manager/multiview-presets.ts
src/api/manager/multiviews.ts
src/api/manager/productions.ts
src/api/manager/workflow.ts
src/app/api/manager/multiview-presets/route.ts
src/app/api/manager/multiviewersOnRunningProduction/[id]/route.ts
src/app/api/manager/multiviewersOnRunningProduction/route.ts
src/app/api/manager/multiviews/route.tsx
src/app/production/[id]/page.tsx
src/components/modal/Modal.tsx
src/components/modal/UpdateMultiviewersModal.tsx
src/components/modal/configureMultiviewModal/ConfigureMultiviewButton.tsx
src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx
src/components/modal/configureMultiviewModal/MultiviewSettings.tsx
src/components/startProduction/StartProductionButton.tsx
src/hooks/monitoring.ts
src/hooks/multiviewPreset.ts
src/hooks/workflow.ts
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/multiview.ts
src/interfaces/preset.ts

This PR makes it possible to add, update and remove multiviewers when a production is running.
Also containing minor fixes:
- Buttons for multiview-config and start production are disabled when no pipelines have been selected.
- Commented out code with TODOs has been removed
View when preparing production:
View when running production:
The configuration looks the same when on a running production and not, but when saving the config you get a warning to confirm that you are about to updated a running config:

feat: added possibility to add, change and remove multiviewers on running production

---

src/api/manager/multiviews.ts

This solves the bug where if you have layouts with the same name, but in different productions, the latter one will replace the former one.

fix: added id check to db-seach

---

src/api/ateliereLive/pipelines/multiviews/multiviews.ts
src/api/ateliereLive/pipelines/pipelines.ts
src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx
src/components/modal/configureMultiviewModal/MultiviewSettings.tsx
src/components/modal/configureOutputModal/PipelineOutputConfig.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts
src/interfaces/multiview.ts

Makes it possible to add a stream-id to multiviewers
Casts an error if there is duplicate values, not including ''.
Also fixes the problem with local-ip when creating a output-stream during caller-mode.

feat/add stream-id to multiview

---

src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx

No error when stream-id is missing but still shows error if duplicate id:s

fix: solved error on empty stream id-problem

---

src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx
src/components/modal/configureMultiviewModal/MultiviewLayoutSettings/MultiviewLayoutSettings.tsx
src/components/modal/configureMultiviewModal/MultiviewSettings.tsx

This solves the problem with multiviewer-config not updating with latest layout and if a layout have been saved in the config before, then the layout now gets updated to latest version.

fix: multiview config updates with latest layout on layout-modal close and save

---

src/components/modal/configureMultiviewModal/ConfigureMultiviewModal.tsx
src/components/modal/configureMultiviewModal/MultiviewSettings.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts

When setting up the multiview it is now possible to remove all values from the fields "Kilobit rate", "Port" and "IP", this will trigger a red border around the field warning the user that this will not be a valid submit. If the user tries to save anyway this will trigger a error-message telling the user what needs to be corrected in order to save.

fix: possible to insert empty value on multiview config, with error

---

src/components/inventory/editView/AudioChannels/AudioChannels.tsx
src/components/inventory/editView/AudioChannels/NumberInput.tsx
src/components/inventory/editView/AudioChannels/Outputs.tsx
src/components/inventory/editView/EditView.tsx
src/components/inventory/editView/UpdateButtons.tsx
src/i18n/locales/sv.ts

When doing audio-config on a source it is now possible to add duplicated fields, to enable possibility to add numbers higher than 9.
If a duplicate number is entered then the 'save'-button is disabled and the duplicate fields are turned red. The error-text has "short term memory" so it alarms when you enter a faulty value and when you enter a correct value in the field next to it then the text goes away, but the red field still remains.
Corrected misspelling of swedish translation.

fix: audio-bugs on inventory-page

---

src/app/production/[id]/page.tsx
src/components/icons/Icons.tsx
src/components/inventory/Inventory.tsx
src/components/sourceList/SourceList.tsx
src/components/sourceListItem/SourceListItem.tsx
src/components/sourceListItem/SourceListItemThumbnail.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts

The button itself is obsolete since the entire source-card is made into a click-area. So removed the button and added an icon to the top corner of the source-card, to guide the user into clicking the card.
A pen-icon instead of "edit" for the inventory-page:
A plus-icon instead of "add" for the production-page:
- Removed some un-used code
- Adjusted width to stop the overlapping-problem on production-page and made all components fit the screen. There were some issues with components being pushed out to the right if all components were shown.

fix/ edit button gets wrapped

---

next.config.js
src/i18n/locales/en.ts

- Renames 'Add Ingest' to 'Add Ingested' (The Swedish name can remain the same)
- Adds a Permissions-Policy header to next.config.js to enable copy to clipboard in the deployed version of the app

fix: rename add ingest and copy error

---

src/components/modal/renderingEngineModals/CreateHtmlModal.tsx

It should not be possible to add a html to a production if the height or width are smaller than 20, there was a bug with that error handeling.

fix: bug html creation

---

src/api/manager/workflow.ts

Only gets the renderingEngine for pipelines if there are html and media sources in the production

fix: only get rendering engine if html/media exist

---

src/app/production/[id]/page.tsx
src/components/sourceList/SourceList.tsx
src/components/sourceListItem/SourceListItem.tsx

Fixes the issue that the source list in both inventory and production page was cut off at the bottom, so that information on the last list item did not show.
Before Inventory:
After Inventory:
Before Production page:
After Production page:

fix: source list cut off bug

---

src/api/manager/job/syncInventory.ts

When a srt-source is created it does not have any info on video or audio, this gets added when the stream is activated. This fetch pushes the new metadata to the db when a running stream is detected.

fix: when srt-source is active it updates db with metadata

---

src/app/production/[id]/page.tsx

There was a problem before that if you removed a source from a RUNNING production, the source was removed only from production.sources but not from production.production_settings.pipelines.pipeline.sources, this PR solves that.

fix: sources not being removed from pipeline

---

src/hooks/useMultiviewDefaultPresets.tsx

If the user checks the "clear layout"-checkbox then the input-slots are set to 0 on all views. Fixes the bug where production-sources still would appear on the multiview even though layout would appear empty.

fix: input-slot is set to 0 if is-checked is true

---

src/api/ateliereLive/pipelines/streams/streams.ts
src/hooks/useUpdateSourceInputSlotOnMultiviewLayouts.tsx

This fixes the bug where production-source labels are reset to source-names on multiviews on running productions, when updating alignment or latency on sources or when updating the multiview-layout.
This fix also updates the labels on all layouts connected to that production, if you update the label after the layout has been created.

fix: labels in multiview got overwritten by source-name

---

src/app/production/[id]/page.tsx

Solves the issue that if you changed a name of a source in inventory, the name change did not follow when you added the source to a production.
Before:
After:

fix: show updated inventory name in production

---

src/api/manager/job/syncInventory.ts

Fixes the bug where audio-mapping gets overwritten on reload or page-changes.

fix: sync-inventory updated to not overwrite excisting mapping

---

src/api/ateliereLive/pipelines/streams/streams.ts
src/api/manager/job/syncInventory.ts
src/components/production/sources/ProductionSources.tsx
src/hooks/useMultiviewDefaultPresets.tsx
src/hooks/useUpdateSourceInputSlotOnMultiviewLayouts.tsx

- sync-inventory updated to not overwrite existing audio-mapping (4000c009c85648d7767812164bcfcf4ed74255fe)
- show updated inventory name in production (d01508737effe1e3e0c1903bce25e840c7656905)
- labels in multiview got overwritten by source-name (f5453f09a3770884e169c58fa23355ed17464e3e)
- input-slot is set to 0 if is-checked is true (c297c57879f0af8ea2c721bdac1484ef86bcd03c)

fix: added bug-fixes from main

---

src/app/api/manager/ingests/source_id/[ingest_name]/[ingest_source_name]/route.ts
src/components/modal/ConfigureAlignmentLatencyModal.tsx
src/components/sourceCard/SourceCard.tsx

This PR solves the issue of:
1. The sourceId not being set correctly / at all for an inactive production. This led to all sourceIds being set to 0 which meant other pipeline sources where overrided and if you added latency/alignment settings to one, it updated the settings for the wrong source in the database.
2. The config-button is only supposed to show if pipelines are selected. The check only checked if pipeline Ids were undefined, but now instead they were empty strings, so the button showed anyway.

fix: New UI: bug sourceId not setting correctly

---

src/components/modal/configureOutputModal/Decision.tsx
src/components/modal/multiviewLayoutSetup/MultiviewLayoutSetup.tsx
src/components/modal/multiviewLayoutSetup/MultiviewLayoutSetupButton.tsx
src/components/modal/multiviewLayoutSetup/MultiviewSettings.tsx
src/components/production/multiviews/ProductionMultiviews.tsx
src/hooks/multiviewLayout.ts
src/hooks/multiviews.ts
src/hooks/productions.ts
src/hooks/useConfigureMultiviewLayout.tsx
src/hooks/useGetFirstEmptySlot.ts
src/hooks/useMultiviewDefaultPresets.tsx
src/i18n/locales/en.ts
src/i18n/locales/sv.ts

- The layout-modal shows up
- Some code related to the old structure is removed
- Available layouts gets populated and added to the layout-dropdown
- A lot of resets is added to make the states and hooks behave as expected
- Bug-fix from main is added to make "clear layout" set input-slot to 0
- Set block from removing layouts saved in productions:

fix: removed some unnecessary code and got layout-setup to work

---

src/app/api/manager/srt/[ingest_name]/[ingest_source_name]/route.ts
src/app/api/manager/srt/[ingest_uuid]/[ingest_source_id]/route.ts
src/hooks/sources/useDeleteSource.tsx

If an ingest has been restarted the SRT-information is then lost from the API, this pr handles the missing SRT-information and the source is only deleted from DB and not trying to delete it from API.

fix: handle missing srt-source in api on delete

---

src/app/production/[id]/page.tsx

This fixes the production-error that the ui doesn't know that a source has been added if the db-fetch fails after the api-fetch has been successful in adding or removing the source to the running production.

fix: added a retry to the database-fetches made after api-fetch

---

src/components/sourceCards/SourceCards.tsx

Solves the problem of ingest sources getting incorrect types in the production after drag and drop

fix: correct source type drag and drop

---

src/app/production/[id]/page.tsx
src/hooks/items/removeSetupItem.ts

If two sources with the same IDs from different ingests were in the same production, there was a problem that deleting one deleted both from the database on production.production_settings.pipelines.pipeline.sources. This PR fixes that issue.

fix: bug with deleting a source if another source with same id present in production

---

src/components/modal/configureMultiviewModal/MultiviewLayoutSettings/RemoveLayoutButton.tsx

This fix disables the remove-layout-button, so a user can't accidentally remove a layout during a running production.
Also minor fix, updated function-name to make more sense.

fix: disabled remove-button when it is hidden
